version: '3'
services:
    core:
        build:
            context: .
            dockerfile: Dockerfile
        image: bot-academy/core-api
        container_name: core
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: core-api
            SERVICE_TAGS: dev
        working_dir: /var/www
        links:
            - mysql
        volumes:
            - ./:/var/www
        ports:
            - "8001:80"
        networks:
            - api-network

    #MySQL Service
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: 'mysql_user'
            MYSQL_PASSWORD: '12345'
            MYSQL_DATABASE: core
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_ROOT_PASSWORD: 12345
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - mysql:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - api-network

#Docker Networks
networks:
    api-network:
        driver: bridge

#Volumes
volumes:
    mysql:
        driver: local
